HINT_DICT = {
    'smt': r"smt",
    'hint': r"hint",
    'my_hint': r"try norm_num [*]; try field_simp [*] at *; try ring_nf at *; try nlinarith",
    "my_hint_v0.1": r"try field_simp [*] at *; try norm_num [*]; try nlinarith",
    "my_hint_v1.0": r"field_simp [*] at * <;> try ring",
    "my_hint_v1.1": r"field_simp <;> try ring",
    "my_hint_v1.2": r"field_simp [*] at * <;> try nlinarith",
    "my_hint_v1.3": r"field_simp <;> try nlinarith",
    'aesop': r"aesop",
    'aesop_v0.1': r"try aesop; try norm_num [*]",
    'omega': r"omega",
    'nlinarith': r"nlinarith",
    "linarith": r"linarith",
    "ring_nf": r"ring_nf",
    "ring": r"ring",
    "simp_all": r"simp_all",
    "norm_cast": r"norm_cast",
    "norm_num": r"norm_num",
    "norm_num_all": r"norm_num [*] at *",
    "field_simp": r"field_simp",
    "field_simp_all": r"field_simp [*] at *",
    "native_decide": r"native_decide",
    "bound": r"bound",
    "leanhammer": r"hammer",
    "leanhammer_0": r"hammer {aesopPremises := 0, autoPremises := 0}",
    "leanhammer_1": r"hammer {aesopPremises := 1, autoPremises := 1}",
    "leanhammer_2": r"hammer {aesopPremises := 2, autoPremises := 2}",
    "leanhammer_3": r"hammer {aesopPremises := 3, autoPremises := 3}",
    "leanhammer_4": r"hammer {aesopPremises := 4, autoPremises := 4}",
    "leanhammer_5": r"hammer {aesopPremises := 5, autoPremises := 5}",
    None: None,
    "dummy": None
}

RECIPE2HAMMER_LIST = {
    "dummy": ["dummy"],
    "mix": ["bound", "nlinarith", "simp_all", "field_simp_all", "omega", "my_hint", "aesop"],
    "mix2": ["aesop", "my_hint", "omega"],
    "hammer0": ["leanhammer_0"],
    "mixh0_v1": ["simp_all", "field_simp_all", "linarith", "leanhammer_0",  "norm_num", "ring_nf", "omega"],
    "mixh0_v2": ["simp_all", "field_simp_all", "nlinarith", "leanhammer_0",  "norm_num", "ring_nf", "omega"],
    "mixh0_v3": ["simp_all", "field_simp_all", "nlinarith", "leanhammer_0",  "norm_num", "ring_nf", "norm_cast", "my_hint", "omega"],
    "mix3": ["field_simp", "field_simp_all", "norm_num", "norm_num_all", "nlinarith", "ring", "norm_cast", "native_decide", "omega", "simp_all", 
    "my_hint_v1.0", "my_hint_v1.1", "my_hint_v1.2", "my_hint_v1.3", "aesop"],
    "mix4": ["field_simp", "norm_num", "nlinarith", "ring", "norm_cast", "native_decide", "omega", "simp_all", 
    "my_hint_v1.2", "my_hint_v1.3"],
}
