proofaug: true
record_pa_reward: true
hammer_recipe: mix4
random_order: true
proofaug_ans_subst: true
proofaug_think_mode: remove
depth_reward_ratio: 0.8
depth_reward_rate: 0.2

remote_timeout: 300
total_timeout: 240
step_timeout: 180
