proofaug: true
record_pa_reward: true
hammer_recipe: mix6
random_order: true
proofaug_ans_subst: true
proofaug_think_mode: remove
subst_rule: maxdepth
part_reward: 0.0
depth_thres: 2
no_truncate: false
conservative: true

remote_timeout: 300
total_timeout: 180
step_timeout: 120
